// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Immutable;

namespace Pulumi.Namecheap
{
    public static class Config
    {
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "IDE1006", Justification = 
        "Double underscore prefix used to avoid conflicts with variable names.")]
        private sealed class __Value<T>
        {
            private readonly Func<T> _getter;
            private T _value = default!;
            private bool _set;

            public __Value(Func<T> getter)
            {
                _getter = getter;
            }

            public T Get() => _set ? _value : _getter();

            public void Set(T value)
            {
                _value = value;
                _set = true;
            }
        }

        private static readonly global::Pulumi.Config __config = new global::Pulumi.Config("namecheap");

        private static readonly __Value<string?> _apiKey = new __Value<string?>(() => __config.Get("apiKey"));
        /// <summary>
        /// The namecheap API key
        /// </summary>
        public static string? ApiKey
        {
            get => _apiKey.Get();
            set => _apiKey.Set(value);
        }

        private static readonly __Value<string?> _apiUser = new __Value<string?>(() => __config.Get("apiUser"));
        /// <summary>
        /// A registered api user for namecheap
        /// </summary>
        public static string? ApiUser
        {
            get => _apiUser.Get();
            set => _apiUser.Set(value);
        }

        private static readonly __Value<string?> _clientIp = new __Value<string?>(() => __config.Get("clientIp"));
        /// <summary>
        /// Client IP address
        /// </summary>
        public static string? ClientIp
        {
            get => _clientIp.Get();
            set => _clientIp.Set(value);
        }

        private static readonly __Value<bool?> _useSandbox = new __Value<bool?>(() => __config.GetBoolean("useSandbox"));
        /// <summary>
        /// Use sandbox API endpoints
        /// </summary>
        public static bool? UseSandbox
        {
            get => _useSandbox.Get();
            set => _useSandbox.Set(value);
        }

        private static readonly __Value<string?> _userName = new __Value<string?>(() => __config.Get("userName"));
        /// <summary>
        /// A registered user name for namecheap
        /// </summary>
        public static string? UserName
        {
            get => _userName.Get();
            set => _userName.Set(value);
        }

    }
}
