// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Namecheap.Outputs
{

    [OutputType]
    public sealed class DomainRecordsRecord
    {
        /// <summary>
        /// Possible values are URL or IP address. The value for this parameter is based on record type
        /// </summary>
        public readonly string Address;
        /// <summary>
        /// Sub-domain/hostname to create the record for
        /// </summary>
        public readonly string Hostname;
        /// <summary>
        /// MX preference for host. Applicable for MX records only
        /// </summary>
        public readonly int? MxPref;
        /// <summary>
        /// Time to live for all record types. Possible values: any value between 60 to 60000
        /// </summary>
        public readonly int? Ttl;
        /// <summary>
        /// Possible values: A, AAAA, ALIAS, CAA, CNAME, MX, MXE, NS, TXT, URL, URL301, FRAME
        /// </summary>
        public readonly string Type;

        [OutputConstructor]
        private DomainRecordsRecord(
            string address,

            string hostname,

            int? mxPref,

            int? ttl,

            string type)
        {
            Address = address;
            Hostname = hostname;
            MxPref = mxPref;
            Ttl = ttl;
            Type = type;
        }
    }
}
