// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Namecheap.Inputs
{

    public sealed class DomainRecordsRecordArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Possible values are URL or IP address. The value for this parameter is based on record type
        /// </summary>
        [Input("address", required: true)]
        public Input<string> Address { get; set; } = null!;

        /// <summary>
        /// Sub-domain/hostname to create the record for
        /// </summary>
        [Input("hostname", required: true)]
        public Input<string> Hostname { get; set; } = null!;

        /// <summary>
        /// MX preference for host. Applicable for MX records only
        /// </summary>
        [Input("mxPref")]
        public Input<int>? MxPref { get; set; }

        /// <summary>
        /// Time to live for all record types. Possible values: any value between 60 to 60000
        /// </summary>
        [Input("ttl")]
        public Input<int>? Ttl { get; set; }

        /// <summary>
        /// Possible values: A, AAAA, ALIAS, CAA, CNAME, MX, MXE, NS, TXT, URL, URL301, FRAME
        /// </summary>
        [Input("type", required: true)]
        public Input<string> Type { get; set; } = null!;

        public DomainRecordsRecordArgs()
        {
        }
        public static new DomainRecordsRecordArgs Empty => new DomainRecordsRecordArgs();
    }
}
